# Generated by Django 6.0.3 on 2026-04-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('bigquery', 'BigQuery'), ('graphql', 'GraphQL'), ('postgres', 'PostgreSQL')], max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
